import { title } from 'process'

export const CountriesList = [
    { value: 'AF', label: 'Afghanistan' },
    { value: 'AL', label: 'Albania' },
    { value: 'DZ', label: 'Algeria' },
    { value: 'AS', label: 'American Samoa' },
    { value: 'AD', label: 'Andorra' },
    { value: 'AO', label: 'Angola' },
    { value: 'AI', label: 'Anguilla' },
    { value: 'AQ', label: 'Antarctica' },
    { value: 'AG', label: 'Antigua and Barbuda' },
    { value: 'AR', label: 'Argentina' },
    { value: 'AM', label: 'Armenia' },
    { value: 'AW', label: 'Aruba' },
    { value: 'AU', label: 'Australia' },
    { value: 'AT', label: 'Austria' },
    { value: 'AZ', label: 'Azerbaijan' },
    { value: 'BS', label: 'Bahamas' },
    { value: 'BH', label: 'Bahrain' },
    { value: 'BD', label: 'Bangladesh' },
    { value: 'BB', label: 'Barbados' },
    { value: 'BY', label: 'Belarus' },
    { value: 'BE', label: 'Belgium' },
    { value: 'BZ', label: 'Belize' },
    { value: 'BJ', label: 'Benin' },
    { value: 'BM', label: 'Bermuda' },
    { value: 'BT', label: 'Bhutan' },
    { value: 'BO', label: 'Bolivia' },
    { value: 'BA', label: 'Bosnia and Herzegovina' },
    { value: 'BW', label: 'Botswana' },
    { value: 'BV', label: 'Bouvet Island' },
    { value: 'BR', label: 'Brazil' },
    { value: 'IO', label: 'British Indian Ocean Territory' },
    { value: 'BN', label: 'Brunei Darussalam' },
    { value: 'BG', label: 'Bulgaria' },
    { value: 'BF', label: 'Burkina Faso' },
    { value: 'BI', label: 'Burundi' },
    { value: 'KH', label: 'Cambodia' },
    { value: 'CM', label: 'Cameroon' },
    { value: 'CA', label: 'Canada' },
    { value: 'CV', label: 'Cape Verde' },
    { value: 'KY', label: 'Cayman Islands' },
    { value: 'CF', label: 'Central African Republic' },
    { value: 'TD', label: 'Chad' },
    { value: 'CL', label: 'Chile' },
    { value: 'CN', label: 'China' },
    { value: 'CX', label: 'Christmas Island' },
    { value: 'CC', label: 'Cocos (Keeling) Islands' },
    { value: 'CO', label: 'Colombia' },
    { value: 'KM', label: 'Comoros' },
    { value: 'CG', label: 'Congo' },
    { value: 'CK', label: 'Cook Islands' },
    { value: 'CR', label: 'Costa Rica' },
    { value: 'CI', label: "Cote d'Ivoire" },
    { value: 'HR', label: 'Croatia' },
    { value: 'CU', label: 'Cuba' },
    { value: 'CY', label: 'Cyprus' },
    { value: 'CZ', label: 'Czech Republic' },
    { value: 'DK', label: 'Denmark' },
    { value: 'DJ', label: 'Djibouti' },
    { value: 'DM', label: 'Dominica' },
    { value: 'DO', label: 'Dominican Republic' },
    { value: 'TL', label: 'East Timor' },
    { value: 'EC', label: 'Ecuador' },
    { value: 'EG', label: 'Egypt' },
    { value: 'SV', label: 'El Salvador' },
    { value: 'GQ', label: 'Equatorial Guinea' },
    { value: 'ER', label: 'Eritrea' },
    { value: 'EE', label: 'Estonia' },
    { value: 'ET', label: 'Ethiopia' },
    { value: 'EU', label: 'Europe' },
    { value: 'FK', label: 'Falkland Islands (Malvinas)' },
    { value: 'FO', label: 'Faroe Islands' },
    { value: 'FJ', label: 'Fiji' },
    { value: 'FI', label: 'Finland' },
    { value: 'FR', label: 'France' },
    { value: 'GF', label: 'French Guiana' },
    { value: 'PF', label: 'French Polynesia' },
    { value: 'TF', label: 'French Southern Territories' },
    { value: 'GA', label: 'Gabon' },
    { value: 'GM', label: 'Gambia' },
    { value: 'GE', label: 'Georgia' },
    { value: 'DE', label: 'Germany' },
    { value: 'GH', label: 'Ghana' },
    { value: 'GI', label: 'Gibraltar' },
    { value: 'GR', label: 'Greece' },
    { value: 'GL', label: 'Greenland' },
    { value: 'GD', label: 'Grenada' },
    { value: 'GP', label: 'Guadeloupe' },
    { value: 'GU', label: 'Guam' },
    { value: 'GT', label: 'Guatemala' },
    { value: 'GN', label: 'Guinea' },
    { value: 'GW', label: 'Guinea-Bissau' },
    { value: 'GY', label: 'Guyana' },
    { value: 'HT', label: 'Haiti' },
    { value: 'HM', label: 'Heard Island and McDonald Islands' },
    { value: 'VA', label: 'Holy See - Vatican City State' },
    { value: 'HN', label: 'Honduras' },
    { value: 'HK', label: 'Hong Kong' },
    { value: 'HU', label: 'Hungary' },
    { value: 'IS', label: 'Iceland' },
    { value: 'IN', label: 'India' },
    { value: 'ID', label: 'Indonesia' },
    { value: 'IR', label: 'Iran' },
    { value: 'IQ', label: 'Iraq' },
    { value: 'IE', label: 'Ireland' },
    { value: 'IL', label: 'Israel' },
    { value: 'IT', label: 'Italy' },
    { value: 'JM', label: 'Jamaica' },
    { value: 'JP', label: 'Japan' },
    { value: 'JO', label: 'Jordan' },
    { value: 'KZ', label: 'Kazakhstan' },
    { value: 'KE', label: 'Kenya' },
    { value: 'KI', label: 'Kiribati' },
    { value: 'KW', label: 'Kuwait' },
    { value: 'KG', label: 'Kyrgyzstan' },
    { value: 'LA', label: 'Laos' },
    { value: 'LV', label: 'Latvia' },
    { value: 'LB', label: 'Lebanon' },
    { value: 'LS', label: 'Lesotho' },
    { value: 'LR', label: 'Liberia' },
    { value: 'LY', label: 'Libyan Arab Jamahiriya' },
    { value: 'LI', label: 'Liechtenstein' },
    { value: 'LT', label: 'Lithuania' },
    { value: 'LU', label: 'Luxembourg' },
    { value: 'MO', label: 'Macao' },
    { value: 'MK', label: 'Macedonia' },
    { value: 'MG', label: 'Madagascar' },
    { value: 'MW', label: 'Malawi' },
    { value: 'MY', label: 'Malaysia' },
    { value: 'MV', label: 'Maldives' },
    { value: 'ML', label: 'Mali' },
    { value: 'MT', label: 'Malta' },
    { value: 'MH', label: 'Marshall Islands' },
    { value: 'MQ', label: 'Martinique' },
    { value: 'MR', label: 'Mauritania' },
    { value: 'MU', label: 'Mauritius' },
    { value: 'YT', label: 'Mayotte' },
    { value: 'MX', label: 'Mexico' },
    { value: 'FM', label: 'Micronesia - Federated States of' },
    { value: 'MD', label: 'Moldova - Republic of' },
    { value: 'MC', label: 'Monaco' },
    { value: 'MN', label: 'Mongolia' },
    { value: 'ME', label: 'Montenegro' },
    { value: 'MS', label: 'Montserrat' },
    { value: 'MA', label: 'Morocco' },
    { value: 'MZ', label: 'Mozambique' },
    { value: 'MM', label: 'Myanmar' },
    { value: 'NA', label: 'Namibia' },
    { value: 'NR', label: 'Nauru' },
    { value: 'NP', label: 'Nepal' },
    { value: 'NL', label: 'Netherlands' },
    { value: 'AN', label: 'Netherlands Antilles' },
    { value: 'NC', label: 'New Caledonia' },
    { value: 'NZ', label: 'New Zealand' },
    { value: 'NI', label: 'Nicaragua' },
    { value: 'NE', label: 'Niger' },
    { value: 'NG', label: 'Nigeria' },
    { value: 'NU', label: 'Niue' },
    { value: 'NF', label: 'Norfolk Island' },
    { value: 'KP', label: 'North Korea' },
    { value: 'MP', label: 'Northern Mariana Islands' },
    { value: 'NO', label: 'Norway' },
    { value: 'OM', label: 'Oman' },
    { value: 'PK', label: 'Pakistan' },
    { value: 'PW', label: 'Palau' },
    { value: 'PS', label: 'Palestinian Territory' },
    { value: 'PA', label: 'Panama' },
    { value: 'PG', label: 'Papua New Guinea' },
    { value: 'PY', label: 'Paraguay' },
    { value: 'PE', label: 'Peru' },
    { value: 'PH', label: 'Philippines' },
    { value: 'PN', label: 'Pitcairn' },
    { value: 'PL', label: 'Poland' },
    { value: 'PT', label: 'Portugal' },
    { value: 'PR', label: 'Puerto Rico' },
    { value: 'QA', label: 'Qatar' },
    { value: 'RE', label: 'Reunion' },
    { value: 'RO', label: 'Romania' },
    { value: 'RU', label: 'Russian Federation' },
    { value: 'RW', label: 'Rwanda' },
    { value: 'SH', label: 'Saint Helena' },
    { value: 'KN', label: 'Saint Kitts and Nevis' },
    { value: 'LC', label: 'Saint Lucia' },
    { value: 'PM', label: 'Saint Pierre and Miquelon' },
    { value: 'VC', label: 'Saint Vincent and the Grenadines' },
    { value: 'WS', label: 'Samoa' },
    { value: 'SM', label: 'San Marino' },
    { value: 'ST', label: 'Sao Tome and Principe' },
    { value: 'SA', label: 'Saudi Arabia' },
    { value: 'SN', label: 'Senegal' },
    { value: 'RS', label: 'Serbia' },
    { value: 'SC', label: 'Seychelles' },
    { value: 'SL', label: 'Sierra Leone' },
    { value: 'SG', label: 'Singapore' },
    { value: 'SK', label: 'Slovakia' },
    { value: 'SI', label: 'Slovenia' },
    { value: 'SB', label: 'Solomon Islands' },
    { value: 'SO', label: 'Somalia' },
    { value: 'ZA', label: 'South Africa' },
    { value: 'GS', label: 'South Georgia and the South Sandwich Islands' },
    { value: 'KR', label: 'South Korea' },
    { value: 'ES', label: 'Spain' },
    { value: 'LK', label: 'Sri Lanka' },
    { value: 'SD', label: 'Sudan' },
    { value: 'SR', label: 'Suriname' },
    { value: 'SJ', label: 'Svalbard and Jan Mayen' },
    { value: 'SZ', label: 'Swaziland' },
    { value: 'SE', label: 'Sweden' },
    { value: 'CH', label: 'Switzerland' },
    { value: 'SY', label: 'Syrian Arab Republic' },
    { value: 'TW', label: 'Taiwan' },
    { value: 'TJ', label: 'Tajikistan' },
    { value: 'TZ', label: 'Tanzania (United Republic of)' },
    { value: 'TH', label: 'Thailand' },
    { value: 'TG', label: 'Togo' },
    { value: 'TK', label: 'Tokelau' },
    { value: 'TO', label: 'Tonga' },
    { value: 'TT', label: 'Trinidad and Tobago' },
    { value: 'TN', label: 'Tunisia' },
    { value: 'TR', label: 'Turkey' },
    { value: 'TM', label: 'Turkmenistan' },
    { value: 'TC', label: 'Turks and Caicos Islands' },
    { value: 'TV', label: 'Tuvalu' },
    { value: 'X1', label: 'UK - England' },
    { value: 'X3', label: 'UK - Northern Ireland' },
    { value: 'X2', label: 'UK - Scotland' },
    { value: 'X4', label: 'UK - Wales' },
    { value: 'UG', label: 'Uganda' },
    { value: 'UA', label: 'Ukraine' },
    { value: 'AE', label: 'United Arab Emirates' },
    { value: 'GB', label: 'United Kingdom' },
    { value: 'US', label: 'United States' },
    { value: 'UM', label: 'United States Minor Outlying Islands' },
    { value: 'UY', label: 'Uruguay' },
    { value: 'UZ', label: 'Uzbekistan' },
    { value: 'VU', label: 'Vanuatu' },
    { value: 'VE', label: 'Venezuela' },
    { value: 'VN', label: 'Vietnam' },
    { value: 'VG', label: 'Virgin Islands - British' },
    { value: 'VI', label: 'Virgin Islands - U.S.' },
    { value: 'WF', label: 'Wallis and Futuna' },
    { value: 'EH', label: 'Western Sahara' },
    { value: 'YE', label: 'Yemen' },
    { value: 'ZR', label: 'Zaire' },
    { value: 'ZM', label: 'Zambia' },
    { value: 'ZW', label: 'Zimbabwe' },
]

export const TimeZones = [
    { value: 'Africa/Abidjan', label: 'Africa/Abidjan' },
    { value: 'Africa/Accra', label: 'Africa/Accra' },
    { value: 'Africa/Addis_Ababa', label: 'Africa/Addis_Ababa' },
    { value: 'Africa/Algiers', label: 'Africa/Algiers' },
    { value: 'Africa/Asmara', label: 'Africa/Asmara' },
    { value: 'Africa/Bamako', label: 'Africa/Bamako' },
    { value: 'Africa/Bangui', label: 'Africa/Bangui' },
    { value: 'Africa/Banjul', label: 'Africa/Banjul' },
    { value: 'Africa/Bissau', label: 'Africa/Bissau' },
    { value: 'Africa/Blantyre', label: 'Africa/Blantyre' },
    { value: 'Africa/Brazzaville', label: 'Africa/Brazzaville' },
    { value: 'Africa/Bujumbura', label: 'Africa/Bujumbura' },
    { value: 'Africa/Cairo', label: 'Africa/Cairo' },
    { value: 'Africa/Casablanca', label: 'Africa/Casablanca' },
    { value: 'Africa/Ceuta', label: 'Africa/Ceuta' },
    { value: 'Africa/Conakry', label: 'Africa/Conakry' },
    { value: 'Africa/Dakar', label: 'Africa/Dakar' },
    { value: 'Africa/Dar_es_Salaam', label: 'Africa/Dar_es_Salaam' },
    { value: 'Africa/Djibouti', label: 'Africa/Djibouti' },
    { value: 'Africa/Douala', label: 'Africa/Douala' },
    { value: 'Africa/El_Aaiun', label: 'Africa/El_Aaiun' },
    { value: 'Africa/Freetown', label: 'Africa/Freetown' },
    { value: 'Africa/Gaborone', label: 'Africa/Gaborone' },
    { value: 'Africa/Harare', label: 'Africa/Harare' },
    { value: 'Africa/Johannesburg', label: 'Africa/Johannesburg' },
    { value: 'Africa/Juba', label: 'Africa/Juba' },
    { value: 'Africa/Kampala', label: 'Africa/Kampala' },
    { value: 'Africa/Khartoum', label: 'Africa/Khartoum' },
    { value: 'Africa/Kigali', label: 'Africa/Kigali' },
    { value: 'Africa/Kinshasa', label: 'Africa/Kinshasa' },
    { value: 'Africa/Lagos', label: 'Africa/Lagos' },
    { value: 'Africa/Libreville', label: 'Africa/Libreville' },
    { value: 'Africa/Lome', label: 'Africa/Lome' },
    { value: 'Africa/Luanda', label: 'Africa/Luanda' },
    { value: 'Africa/Lubumbashi', label: 'Africa/Lubumbashi' },
    { value: 'Africa/Lusaka', label: 'Africa/Lusaka' },
    { value: 'Africa/Malabo', label: 'Africa/Malabo' },
    { value: 'Africa/Maputo', label: 'Africa/Maputo' },
    { value: 'Africa/Maseru', label: 'Africa/Maseru' },
    { value: 'Africa/Mbabane', label: 'Africa/Mbabane' },
    { value: 'Africa/Mogadishu', label: 'Africa/Mogadishu' },
    { value: 'Africa/Monrovia', label: 'Africa/Monrovia' },
    { value: 'Africa/Nairobi', label: 'Africa/Nairobi' },
    { value: 'Africa/Ndjamena', label: 'Africa/Ndjamena' },
    { value: 'Africa/Niamey', label: 'Africa/Niamey' },
    { value: 'Africa/Nouakchott', label: 'Africa/Nouakchott' },
    { value: 'Africa/Ouagadougou', label: 'Africa/Ouagadougou' },
    { value: 'Africa/Porto-Novo', label: 'Africa/Porto-Novo' },
    { value: 'Africa/Sao_Tome', label: 'Africa/Sao_Tome' },
    { value: 'Africa/Tripoli', label: 'Africa/Tripoli' },
    { value: 'Africa/Tunis', label: 'Africa/Tunis' },
    { value: 'Africa/Windhoek', label: 'Africa/Windhoek' },
    { value: 'America/Adak', label: 'America/Adak' },
    { value: 'America/Anchorage', label: 'America/Anchorage' },
    { value: 'America/Anguilla', label: 'America/Anguilla' },
    { value: 'America/Antigua', label: 'America/Antigua' },
    { value: 'America/Araguaina', label: 'America/Araguaina' },
    {
        value: 'America/Argentina/Buenos_Aires',
        label: 'America/Argentina/Buenos_Aires',
    },
    {
        value: 'America/Argentina/Catamarca',
        label: 'America/Argentina/Catamarca',
    },
    { value: 'America/Argentina/Cordoba', label: 'America/Argentina/Cordoba' },
    { value: 'America/Argentina/Jujuy', label: 'America/Argentina/Jujuy' },
    {
        value: 'America/Argentina/La_Rioja',
        label: 'America/Argentina/La_Rioja',
    },
    { value: 'America/Argentina/Mendoza', label: 'America/Argentina/Mendoza' },
    {
        value: 'America/Argentina/Rio_Gallegos',
        label: 'America/Argentina/Rio_Gallegos',
    },
    { value: 'America/Argentina/Salta', label: 'America/Argentina/Salta' },
    {
        value: 'America/Argentina/San_Juan',
        label: 'America/Argentina/San_Juan',
    },
    {
        value: 'America/Argentina/San_Luis',
        label: 'America/Argentina/San_Luis',
    },
    { value: 'America/Argentina/Tucuman', label: 'America/Argentina/Tucuman' },
    { value: 'America/Argentina/Ushuaia', label: 'America/Argentina/Ushuaia' },
    { value: 'America/Aruba', label: 'America/Aruba' },
    { value: 'America/Asuncion', label: 'America/Asuncion' },
    { value: 'America/Atikokan', label: 'America/Atikokan' },
    { value: 'America/Bahia', label: 'America/Bahia' },
    { value: 'America/Bahia_Banderas', label: 'America/Bahia_Banderas' },
    { value: 'America/Barbados', label: 'America/Barbados' },
    { value: 'America/Belem', label: 'America/Belem' },
    { value: 'America/Belize', label: 'America/Belize' },
    { value: 'America/Blanc-Sablon', label: 'America/Blanc-Sablon' },
    { value: 'America/Boa_Vista', label: 'America/Boa_Vista' },
    { value: 'America/Bogota', label: 'America/Bogota' },
    { value: 'America/Boise', label: 'America/Boise' },
    { value: 'America/Cambridge_Bay', label: 'America/Cambridge_Bay' },
    { value: 'America/Campo_Grande', label: 'America/Campo_Grande' },
    { value: 'America/Cancun', label: 'America/Cancun' },
    { value: 'America/Caracas', label: 'America/Caracas' },
    { value: 'America/Cayenne', label: 'America/Cayenne' },
    { value: 'America/Cayman', label: 'America/Cayman' },
    { value: 'America/Chicago', label: 'America/Chicago' },
    { value: 'America/Chihuahua', label: 'America/Chihuahua' },
    { value: 'America/Ciudad_Juarez', label: 'America/Ciudad_Juarez' },
    { value: 'America/Costa_Rica', label: 'America/Costa_Rica' },
    { value: 'America/Creston', label: 'America/Creston' },
    { value: 'America/Cuiaba', label: 'America/Cuiaba' },
    { value: 'America/Curacao', label: 'America/Curacao' },
    { value: 'America/Danmarkshavn', label: 'America/Danmarkshavn' },
    { value: 'America/Dawson', label: 'America/Dawson' },
    { value: 'America/Dawson_Creek', label: 'America/Dawson_Creek' },
    { value: 'America/Denver', label: 'America/Denver' },
    { value: 'America/Detroit', label: 'America/Detroit' },
    { value: 'America/Dominica', label: 'America/Dominica' },
    { value: 'America/Edmonton', label: 'America/Edmonton' },
    { value: 'America/Eirunepe', label: 'America/Eirunepe' },
    { value: 'America/El_Salvador', label: 'America/El_Salvador' },
    { value: 'America/Fort_Nelson', label: 'America/Fort_Nelson' },
    { value: 'America/Fortaleza', label: 'America/Fortaleza' },
    { value: 'America/Glace_Bay', label: 'America/Glace_Bay' },
    { value: 'America/Goose_Bay', label: 'America/Goose_Bay' },
    { value: 'America/Grand_Turk', label: 'America/Grand_Turk' },
    { value: 'America/Grenada', label: 'America/Grenada' },
    { value: 'America/Guadeloupe', label: 'America/Guadeloupe' },
    { value: 'America/Guatemala', label: 'America/Guatemala' },
    { value: 'America/Guayaquil', label: 'America/Guayaquil' },
    { value: 'America/Guyana', label: 'America/Guyana' },
    { value: 'America/Halifax', label: 'America/Halifax' },
    { value: 'America/Havana', label: 'America/Havana' },
    { value: 'America/Hermosillo', label: 'America/Hermosillo' },
    {
        value: 'America/Indiana/Indianapolis',
        label: 'America/Indiana/Indianapolis',
    },
    { value: 'America/Indiana/Knox', label: 'America/Indiana/Knox' },
    { value: 'America/Indiana/Marengo', label: 'America/Indiana/Marengo' },
    {
        value: 'America/Indiana/Petersburg',
        label: 'America/Indiana/Petersburg',
    },
    { value: 'America/Indiana/Tell_City', label: 'America/Indiana/Tell_City' },
    { value: 'America/Indiana/Vevay', label: 'America/Indiana/Vevay' },
    { value: 'America/Indiana/Vincennes', label: 'America/Indiana/Vincennes' },
    { value: 'America/Indiana/Winamac', label: 'America/Indiana/Winamac' },
    { value: 'America/Inuvik', label: 'America/Inuvik' },
    { value: 'America/Iqaluit', label: 'America/Iqaluit' },
    { value: 'America/Jamaica', label: 'America/Jamaica' },
    { value: 'America/Juneau', label: 'America/Juneau' },
    {
        value: 'America/Kentucky/Louisville',
        label: 'America/Kentucky/Louisville',
    },
    {
        value: 'America/Kentucky/Monticello',
        label: 'America/Kentucky/Monticello',
    },
    { value: 'America/Kralendijk', label: 'America/Kralendijk' },
    { value: 'America/La_Paz', label: 'America/La_Paz' },
    { value: 'America/Lima', label: 'America/Lima' },
    { value: 'America/Los_Angeles', label: 'America/Los_Angeles' },
    { value: 'America/Lower_Princes', label: 'America/Lower_Princes' },
    { value: 'America/Maceio', label: 'America/Maceio' },
    { value: 'America/Managua', label: 'America/Managua' },
    { value: 'America/Manaus', label: 'America/Manaus' },
    { value: 'America/Marigot', label: 'America/Marigot' },
    { value: 'America/Martinique', label: 'America/Martinique' },
    { value: 'America/Matamoros', label: 'America/Matamoros' },
    { value: 'America/Mazatlan', label: 'America/Mazatlan' },
    { value: 'America/Menominee', label: 'America/Menominee' },
    { value: 'America/Merida', label: 'America/Merida' },
    { value: 'America/Metlakatla', label: 'America/Metlakatla' },
    { value: 'America/Mexico_City', label: 'America/Mexico_City' },
    { value: 'America/Miquelon', label: 'America/Miquelon' },
    { value: 'America/Moncton', label: 'America/Moncton' },
    { value: 'America/Monterrey', label: 'America/Monterrey' },
    { value: 'America/Montevideo', label: 'America/Montevideo' },
    { value: 'America/Montserrat', label: 'America/Montserrat' },
    { value: 'America/Nassau', label: 'America/Nassau' },
    { value: 'America/New_York', label: 'America/New_York' },
    { value: 'America/Nome', label: 'America/Nome' },
    { value: 'America/Noronha', label: 'America/Noronha' },
    {
        value: 'America/North_Dakota/Beulah',
        label: 'America/North_Dakota/Beulah',
    },
    {
        value: 'America/North_Dakota/Center',
        label: 'America/North_Dakota/Center',
    },
    {
        value: 'America/North_Dakota/New_Salem',
        label: 'America/North_Dakota/New_Salem',
    },
    { value: 'America/Nuuk', label: 'America/Nuuk' },
    { value: 'America/Ojinaga', label: 'America/Ojinaga' },
    { value: 'America/Panama', label: 'America/Panama' },
    { value: 'America/Paramaribo', label: 'America/Paramaribo' },
    { value: 'America/Phoenix', label: 'America/Phoenix' },
    { value: 'America/Port-au-Prince', label: 'America/Port-au-Prince' },
    { value: 'America/Port_of_Spain', label: 'America/Port_of_Spain' },
    { value: 'America/Porto_Velho', label: 'America/Porto_Velho' },
    { value: 'America/Puerto_Rico', label: 'America/Puerto_Rico' },
    { value: 'America/Punta_Arenas', label: 'America/Punta_Arenas' },
    { value: 'America/Rankin_Inlet', label: 'America/Rankin_Inlet' },
    { value: 'America/Recife', label: 'America/Recife' },
    { value: 'America/Regina', label: 'America/Regina' },
    { value: 'America/Resolute', label: 'America/Resolute' },
    { value: 'America/Rio_Branco', label: 'America/Rio_Branco' },
    { value: 'America/Santarem', label: 'America/Santarem' },
    { value: 'America/Santiago', label: 'America/Santiago' },
    { value: 'America/Santo_Domingo', label: 'America/Santo_Domingo' },
    { value: 'America/Sao_Paulo', label: 'America/Sao_Paulo' },
    { value: 'America/Scoresbysund', label: 'America/Scoresbysund' },
    { value: 'America/Sitka', label: 'America/Sitka' },
    { value: 'America/St_Barthelemy', label: 'America/St_Barthelemy' },
    { value: 'America/St_Johns', label: 'America/St_Johns' },
    { value: 'America/St_Kitts', label: 'America/St_Kitts' },
    { value: 'America/St_Lucia', label: 'America/St_Lucia' },
    { value: 'America/St_Thomas', label: 'America/St_Thomas' },
    { value: 'America/St_Vincent', label: 'America/St_Vincent' },
    { value: 'America/Swift_Current', label: 'America/Swift_Current' },
    { value: 'America/Tegucigalpa', label: 'America/Tegucigalpa' },
    { value: 'America/Thule', label: 'America/Thule' },
    { value: 'America/Tijuana', label: 'America/Tijuana' },
    { value: 'America/Toronto', label: 'America/Toronto' },
    { value: 'America/Tortola', label: 'America/Tortola' },
    { value: 'America/Vancouver', label: 'America/Vancouver' },
    { value: 'America/Whitehorse', label: 'America/Whitehorse' },
    { value: 'America/Winnipeg', label: 'America/Winnipeg' },
    { value: 'America/Yakutat', label: 'America/Yakutat' },
    { value: 'Antarctica/Casey', label: 'Antarctica/Casey' },
    { value: 'Antarctica/Davis', label: 'Antarctica/Davis' },
    { value: 'Antarctica/DumontDUrville', label: 'Antarctica/DumontDUrville' },
    { value: 'Antarctica/Macquarie', label: 'Antarctica/Macquarie' },
    { value: 'Antarctica/Mawson', label: 'Antarctica/Mawson' },
    { value: 'Antarctica/McMurdo', label: 'Antarctica/McMurdo' },
    { value: 'Antarctica/Palmer', label: 'Antarctica/Palmer' },
    { value: 'Antarctica/Rothera', label: 'Antarctica/Rothera' },
    { value: 'Antarctica/Syowa', label: 'Antarctica/Syowa' },
    { value: 'Antarctica/Troll', label: 'Antarctica/Troll' },
    { value: 'Antarctica/Vostok', label: 'Antarctica/Vostok' },
    { value: 'Arctic/Longyearbyen', label: 'Arctic/Longyearbyen' },
    { value: 'Asia/Aden', label: 'Asia/Aden' },
    { value: 'Asia/Almaty', label: 'Asia/Almaty' },
    { value: 'Asia/Amman', label: 'Asia/Amman' },
    { value: 'Asia/Anadyr', label: 'Asia/Anadyr' },
    { value: 'Asia/Aqtau', label: 'Asia/Aqtau' },
    { value: 'Asia/Aqtobe', label: 'Asia/Aqtobe' },
    { value: 'Asia/Ashgabat', label: 'Asia/Ashgabat' },
    { value: 'Asia/Atyrau', label: 'Asia/Atyrau' },
    { value: 'Asia/Baghdad', label: 'Asia/Baghdad' },
    { value: 'Asia/Bahrain', label: 'Asia/Bahrain' },
    { value: 'Asia/Baku', label: 'Asia/Baku' },
    { value: 'Asia/Bangkok', label: 'Asia/Bangkok' },
    { value: 'Asia/Barnaul', label: 'Asia/Barnaul' },
    { value: 'Asia/Beirut', label: 'Asia/Beirut' },
    { value: 'Asia/Bishkek', label: 'Asia/Bishkek' },
    { value: 'Asia/Brunei', label: 'Asia/Brunei' },
    { value: 'Asia/Chita', label: 'Asia/Chita' },
    { value: 'Asia/Choibalsan', label: 'Asia/Choibalsan' },
    { value: 'Asia/Colombo', label: 'Asia/Colombo' },
    { value: 'Asia/Damascus', label: 'Asia/Damascus' },
    { value: 'Asia/Dhaka', label: 'Asia/Dhaka' },
    { value: 'Asia/Dili', label: 'Asia/Dili' },
    { value: 'Asia/Dubai', label: 'Asia/Dubai' },
    { value: 'Asia/Dushanbe', label: 'Asia/Dushanbe' },
    { value: 'Asia/Famagusta', label: 'Asia/Famagusta' },
    { value: 'Asia/Gaza', label: 'Asia/Gaza' },
    { value: 'Asia/Hebron', label: 'Asia/Hebron' },
    { value: 'Asia/Ho_Chi_Minh', label: 'Asia/Ho_Chi_Minh' },
    { value: 'Asia/Hong_Kong', label: 'Asia/Hong_Kong' },
    { value: 'Asia/Hovd', label: 'Asia/Hovd' },
    { value: 'Asia/Irkutsk', label: 'Asia/Irkutsk' },
    { value: 'Asia/Jakarta', label: 'Asia/Jakarta' },
    { value: 'Asia/Jayapura', label: 'Asia/Jayapura' },
    { value: 'Asia/Jerusalem', label: 'Asia/Jerusalem' },
    { value: 'Asia/Kabul', label: 'Asia/Kabul' },
    { value: 'Asia/Kamchatka', label: 'Asia/Kamchatka' },
    { value: 'Asia/Karachi', label: 'Asia/Karachi' },
    { value: 'Asia/Kathmandu', label: 'Asia/Kathmandu' },
    { value: 'Asia/Khandyga', label: 'Asia/Khandyga' },
    { value: 'Asia/Kolkata', label: 'Asia/Kolkata' },
    { value: 'Asia/Krasnoyarsk', label: 'Asia/Krasnoyarsk' },
    { value: 'Asia/Kuala_Lumpur', label: 'Asia/Kuala_Lumpur' },
    { value: 'Asia/Kuching', label: 'Asia/Kuching' },
    { value: 'Asia/Kuwait', label: 'Asia/Kuwait' },
    { value: 'Asia/Macau', label: 'Asia/Macau' },
    { value: 'Asia/Magadan', label: 'Asia/Magadan' },
    { value: 'Asia/Makassar', label: 'Asia/Makassar' },
    { value: 'Asia/Manila', label: 'Asia/Manila' },
    { value: 'Asia/Muscat', label: 'Asia/Muscat' },
    { value: 'Asia/Nicosia', label: 'Asia/Nicosia' },
    { value: 'Asia/Novokuznetsk', label: 'Asia/Novokuznetsk' },
    { value: 'Asia/Novosibirsk', label: 'Asia/Novosibirsk' },
    { value: 'Asia/Omsk', label: 'Asia/Omsk' },
    { value: 'Asia/Oral', label: 'Asia/Oral' },
    { value: 'Asia/Phnom_Penh', label: 'Asia/Phnom_Penh' },
    { value: 'Asia/Pontianak', label: 'Asia/Pontianak' },
    { value: 'Asia/Pyongyang', label: 'Asia/Pyongyang' },
    { value: 'Asia/Qatar', label: 'Asia/Qatar' },
    { value: 'Asia/Qostanay', label: 'Asia/Qostanay' },
    { value: 'Asia/Qyzylorda', label: 'Asia/Qyzylorda' },
    { value: 'Asia/Riyadh', label: 'Asia/Riyadh' },
    { value: 'Asia/Sakhalin', label: 'Asia/Sakhalin' },
    { value: 'Asia/Samarkand', label: 'Asia/Samarkand' },
    { value: 'Asia/Seoul', label: 'Asia/Seoul' },
    { value: 'Asia/Shanghai', label: 'Asia/Shanghai' },
    { value: 'Asia/Singapore', label: 'Asia/Singapore' },
    { value: 'Asia/Srednekolymsk', label: 'Asia/Srednekolymsk' },
    { value: 'Asia/Taipei', label: 'Asia/Taipei' },
    { value: 'Asia/Tashkent', label: 'Asia/Tashkent' },
    { value: 'Asia/Tbilisi', label: 'Asia/Tbilisi' },
    { value: 'Asia/Tehran', label: 'Asia/Tehran' },
    { value: 'Asia/Thimphu', label: 'Asia/Thimphu' },
    { value: 'Asia/Tokyo', label: 'Asia/Tokyo' },
    { value: 'Asia/Tomsk', label: 'Asia/Tomsk' },
    { value: 'Asia/Ulaanbaatar', label: 'Asia/Ulaanbaatar' },
    { value: 'Asia/Urumqi', label: 'Asia/Urumqi' },
    { value: 'Asia/Ust-Nera', label: 'Asia/Ust-Nera' },
    { value: 'Asia/Vientiane', label: 'Asia/Vientiane' },
    { value: 'Asia/Vladivostok', label: 'Asia/Vladivostok' },
    { value: 'Asia/Yakutsk', label: 'Asia/Yakutsk' },
    { value: 'Asia/Yangon', label: 'Asia/Yangon' },
    { value: 'Asia/Yekaterinburg', label: 'Asia/Yekaterinburg' },
    { value: 'Asia/Yerevan', label: 'Asia/Yerevan' },
    { value: 'Atlantic/Azores', label: 'Atlantic/Azores' },
    { value: 'Atlantic/Bermuda', label: 'Atlantic/Bermuda' },
    { value: 'Atlantic/Canary', label: 'Atlantic/Canary' },
    { value: 'Atlantic/Cape_Verde', label: 'Atlantic/Cape_Verde' },
    { value: 'Atlantic/Faroe', label: 'Atlantic/Faroe' },
    { value: 'Atlantic/Madeira', label: 'Atlantic/Madeira' },
    { value: 'Atlantic/Reykjavik', label: 'Atlantic/Reykjavik' },
    { value: 'Atlantic/South_Georgia', label: 'Atlantic/South_Georgia' },
    { value: 'Atlantic/St_Helena', label: 'Atlantic/St_Helena' },
    { value: 'Atlantic/Stanley', label: 'Atlantic/Stanley' },
    { value: 'Australia/Adelaide', label: 'Australia/Adelaide' },
    { value: 'Australia/Brisbane', label: 'Australia/Brisbane' },
    { value: 'Australia/Broken_Hill', label: 'Australia/Broken_Hill' },
    { value: 'Australia/Darwin', label: 'Australia/Darwin' },
    { value: 'Australia/Eucla', label: 'Australia/Eucla' },
    { value: 'Australia/Hobart', label: 'Australia/Hobart' },
    { value: 'Australia/Lindeman', label: 'Australia/Lindeman' },
    { value: 'Australia/Lord_Howe', label: 'Australia/Lord_Howe' },
    { value: 'Australia/Melbourne', label: 'Australia/Melbourne' },
    { value: 'Australia/Perth', label: 'Australia/Perth' },
    { value: 'Australia/Sydney', label: 'Australia/Sydney' },
    { value: 'Europe/Amsterdam', label: 'Europe/Amsterdam' },
    { value: 'Europe/Andorra', label: 'Europe/Andorra' },
    { value: 'Europe/Astrakhan', label: 'Europe/Astrakhan' },
    { value: 'Europe/Athens', label: 'Europe/Athens' },
    { value: 'Europe/Belgrade', label: 'Europe/Belgrade' },
    { value: 'Europe/Berlin', label: 'Europe/Berlin' },
    { value: 'Europe/Bratislava', label: 'Europe/Bratislava' },
    { value: 'Europe/Brussels', label: 'Europe/Brussels' },
    { value: 'Europe/Bucharest', label: 'Europe/Bucharest' },
    { value: 'Europe/Budapest', label: 'Europe/Budapest' },
    { value: 'Europe/Busingen', label: 'Europe/Busingen' },
    { value: 'Europe/Chisinau', label: 'Europe/Chisinau' },
    { value: 'Europe/Copenhagen', label: 'Europe/Copenhagen' },
    { value: 'Europe/Dublin', label: 'Europe/Dublin' },
    { value: 'Europe/Gibraltar', label: 'Europe/Gibraltar' },
    { value: 'Europe/Guernsey', label: 'Europe/Guernsey' },
    { value: 'Europe/Helsinki', label: 'Europe/Helsinki' },
    { value: 'Europe/Isle_of_Man', label: 'Europe/Isle_of_Man' },
    { value: 'Europe/Istanbul', label: 'Europe/Istanbul' },
    { value: 'Europe/Jersey', label: 'Europe/Jersey' },
    { value: 'Europe/Kaliningrad', label: 'Europe/Kaliningrad' },
    { value: 'Europe/Kirov', label: 'Europe/Kirov' },
    { value: 'Europe/Kyiv', label: 'Europe/Kyiv' },
    { value: 'Europe/Lisbon', label: 'Europe/Lisbon' },
    { value: 'Europe/Ljubljana', label: 'Europe/Ljubljana' },
    { value: 'Europe/London', label: 'Europe/London' },
    { value: 'Europe/Luxembourg', label: 'Europe/Luxembourg' },
    { value: 'Europe/Madrid', label: 'Europe/Madrid' },
    { value: 'Europe/Malta', label: 'Europe/Malta' },
    { value: 'Europe/Mariehamn', label: 'Europe/Mariehamn' },
    { value: 'Europe/Minsk', label: 'Europe/Minsk' },
    { value: 'Europe/Monaco', label: 'Europe/Monaco' },
    { value: 'Europe/Moscow', label: 'Europe/Moscow' },
    { value: 'Europe/Oslo', label: 'Europe/Oslo' },
    { value: 'Europe/Paris', label: 'Europe/Paris' },
    { value: 'Europe/Podgorica', label: 'Europe/Podgorica' },
    { value: 'Europe/Prague', label: 'Europe/Prague' },
    { value: 'Europe/Riga', label: 'Europe/Riga' },
    { value: 'Europe/Rome', label: 'Europe/Rome' },
    { value: 'Europe/Samara', label: 'Europe/Samara' },
    { value: 'Europe/San_Marino', label: 'Europe/San_Marino' },
    { value: 'Europe/Sarajevo', label: 'Europe/Sarajevo' },
    { value: 'Europe/Saratov', label: 'Europe/Saratov' },
    { value: 'Europe/Simferopol', label: 'Europe/Simferopol' },
    { value: 'Europe/Skopje', label: 'Europe/Skopje' },
    { value: 'Europe/Sofia', label: 'Europe/Sofia' },
    { value: 'Europe/Stockholm', label: 'Europe/Stockholm' },
    { value: 'Europe/Tallinn', label: 'Europe/Tallinn' },
    { value: 'Europe/Tirane', label: 'Europe/Tirane' },
    { value: 'Europe/Ulyanovsk', label: 'Europe/Ulyanovsk' },
    { value: 'Europe/Vaduz', label: 'Europe/Vaduz' },
    { value: 'Europe/Vatican', label: 'Europe/Vatican' },
    { value: 'Europe/Vienna', label: 'Europe/Vienna' },
    { value: 'Europe/Vilnius', label: 'Europe/Vilnius' },
    { value: 'Europe/Volgograd', label: 'Europe/Volgograd' },
    { value: 'Europe/Warsaw', label: 'Europe/Warsaw' },
    { value: 'Europe/Zagreb', label: 'Europe/Zagreb' },
    { value: 'Europe/Zurich', label: 'Europe/Zurich' },
    { value: 'Indian/Antananarivo', label: 'Indian/Antananarivo' },
    { value: 'Indian/Chagos', label: 'Indian/Chagos' },
    { value: 'Indian/Christmas', label: 'Indian/Christmas' },
    { value: 'Indian/Cocos', label: 'Indian/Cocos' },
    { value: 'Indian/Comoro', label: 'Indian/Comoro' },
    { value: 'Indian/Kerguelen', label: 'Indian/Kerguelen' },
    { value: 'Indian/Mahe', label: 'Indian/Mahe' },
    { value: 'Indian/Maldives', label: 'Indian/Maldives' },
    { value: 'Indian/Mauritius', label: 'Indian/Mauritius' },
    { value: 'Indian/Mayotte', label: 'Indian/Mayotte' },
    { value: 'Indian/Reunion', label: 'Indian/Reunion' },
    { value: 'Pacific/Apia', label: 'Pacific/Apia' },
    { value: 'Pacific/Auckland', label: 'Pacific/Auckland' },
    { value: 'Pacific/Bougainville', label: 'Pacific/Bougainville' },
    { value: 'Pacific/Chatham', label: 'Pacific/Chatham' },
    { value: 'Pacific/Chuuk', label: 'Pacific/Chuuk' },
    { value: 'Pacific/Easter', label: 'Pacific/Easter' },
    { value: 'Pacific/Efate', label: 'Pacific/Efate' },
    { value: 'Pacific/Fakaofo', label: 'Pacific/Fakaofo' },
    { value: 'Pacific/Fiji', label: 'Pacific/Fiji' },
    { value: 'Pacific/Funafuti', label: 'Pacific/Funafuti' },
    { value: 'Pacific/Galapagos', label: 'Pacific/Galapagos' },
    { value: 'Pacific/Gambier', label: 'Pacific/Gambier' },
    { value: 'Pacific/Guadalcanal', label: 'Pacific/Guadalcanal' },
    { value: 'Pacific/Guam', label: 'Pacific/Guam' },
    { value: 'Pacific/Honolulu', label: 'Pacific/Honolulu' },
    { value: 'Pacific/Kanton', label: 'Pacific/Kanton' },
    { value: 'Pacific/Kiritimati', label: 'Pacific/Kiritimati' },
    { value: 'Pacific/Kosrae', label: 'Pacific/Kosrae' },
    { value: 'Pacific/Kwajalein', label: 'Pacific/Kwajalein' },
    { value: 'Pacific/Majuro', label: 'Pacific/Majuro' },
    { value: 'Pacific/Marquesas', label: 'Pacific/Marquesas' },
    { value: 'Pacific/Midway', label: 'Pacific/Midway' },
    { value: 'Pacific/Nauru', label: 'Pacific/Nauru' },
    { value: 'Pacific/Niue', label: 'Pacific/Niue' },
    { value: 'Pacific/Norfolk', label: 'Pacific/Norfolk' },
    { value: 'Pacific/Noumea', label: 'Pacific/Noumea' },
    { value: 'Pacific/Pago_Pago', label: 'Pacific/Pago_Pago' },
    { value: 'Pacific/Palau', label: 'Pacific/Palau' },
    { value: 'Pacific/Pitcairn', label: 'Pacific/Pitcairn' },
    { value: 'Pacific/Pohnpei', label: 'Pacific/Pohnpei' },
    { value: 'Pacific/Port_Moresby', label: 'Pacific/Port_Moresby' },
    { value: 'Pacific/Rarotonga', label: 'Pacific/Rarotonga' },
    { value: 'Pacific/Saipan', label: 'Pacific/Saipan' },
    { value: 'Pacific/Tahiti', label: 'Pacific/Tahiti' },
    { value: 'Pacific/Tarawa', label: 'Pacific/Tarawa' },
    { value: 'Pacific/Tongatapu', label: 'Pacific/Tongatapu' },
    { value: 'Pacific/Wake', label: 'Pacific/Wake' },
    { value: 'Pacific/Wallis', label: 'Pacific/Wallis' },
    { value: 'UTC', label: 'UTC' },
]

interface TimezonesByCountryType {
    [key: string]: string[]
}
export const TimezonesByCountry: TimezonesByCountryType = {
    ALL: [
        'Africa/Abidjan',
        'Africa/Accra',
        'Africa/Addis_Ababa',
        'Africa/Algiers',
        'Africa/Asmara',
        'Africa/Asmera',
        'Africa/Bamako',
        'Africa/Bangui',
        'Africa/Banjul',
        'Africa/Bissau',
        'Africa/Blantyre',
        'Africa/Brazzaville',
        'Africa/Bujumbura',
        'Africa/Cairo',
        'Africa/Casablanca',
        'Africa/Ceuta',
        'Africa/Conakry',
        'Africa/Dakar',
        'Africa/Dar_es_Salaam',
        'Africa/Djibouti',
        'Africa/Douala',
        'Africa/El_Aaiun',
        'Africa/Freetown',
        'Africa/Gaborone',
        'Africa/Harare',
        'Africa/Johannesburg',
        'Africa/Juba',
        'Africa/Kampala',
        'Africa/Khartoum',
        'Africa/Kigali',
        'Africa/Kinshasa',
        'Africa/Lagos',
        'Africa/Libreville',
        'Africa/Lome',
        'Africa/Luanda',
        'Africa/Lubumbashi',
        'Africa/Lusaka',
        'Africa/Malabo',
        'Africa/Maputo',
        'Africa/Maseru',
        'Africa/Mbabane',
        'Africa/Mogadishu',
        'Africa/Monrovia',
        'Africa/Nairobi',
        'Africa/Ndjamena',
        'Africa/Niamey',
        'Africa/Nouakchott',
        'Africa/Ouagadougou',
        'Africa/Porto-Novo',
        'Africa/Sao_Tome',
        'Africa/Timbuktu',
        'Africa/Tripoli',
        'Africa/Tunis',
        'Africa/Windhoek',
        'America/Adak',
        'America/Anchorage',
        'America/Anguilla',
        'America/Antigua',
        'America/Araguaina',
        'America/Argentina/Buenos_Aires',
        'America/Argentina/Catamarca',
        'America/Argentina/ComodRivadavia',
        'America/Argentina/Cordoba',
        'America/Argentina/Jujuy',
        'America/Argentina/La_Rioja',
        'America/Argentina/Mendoza',
        'America/Argentina/Rio_Gallegos',
        'America/Argentina/Salta',
        'America/Argentina/San_Juan',
        'America/Argentina/San_Luis',
        'America/Argentina/Tucuman',
        'America/Argentina/Ushuaia',
        'America/Aruba',
        'America/Asuncion',
        'America/Atikokan',
        'America/Atka',
        'America/Bahia',
        'America/Bahia_Banderas',
        'America/Barbados',
        'America/Belem',
        'America/Belize',
        'America/Blanc-Sablon',
        'America/Boa_Vista',
        'America/Bogota',
        'America/Boise',
        'America/Buenos_Aires',
        'America/Cambridge_Bay',
        'America/Campo_Grande',
        'America/Cancun',
        'America/Caracas',
        'America/Catamarca',
        'America/Cayenne',
        'America/Cayman',
        'America/Chicago',
        'America/Chihuahua',
        'America/Coral_Harbour',
        'America/Cordoba',
        'America/Costa_Rica',
        'America/Creston',
        'America/Cuiaba',
        'America/Curacao',
        'America/Danmarkshavn',
        'America/Dawson',
        'America/Dawson_Creek',
        'America/Denver',
        'America/Detroit',
        'America/Dominica',
        'America/Edmonton',
        'America/Eirunepe',
        'America/El_Salvador',
        'America/Ensenada',
        'America/Fort_Wayne',
        'America/Fortaleza',
        'America/Glace_Bay',
        'America/Godthab',
        'America/Goose_Bay',
        'America/Grand_Turk',
        'America/Grenada',
        'America/Guadeloupe',
        'America/Guatemala',
        'America/Guayaquil',
        'America/Guyana',
        'America/Halifax',
        'America/Havana',
        'America/Hermosillo',
        'America/Indiana/Indianapolis',
        'America/Indiana/Knox',
        'America/Indiana/Marengo',
        'America/Indiana/Petersburg',
        'America/Indiana/Tell_City',
        'America/Indiana/Vevay',
        'America/Indiana/Vincennes',
        'America/Indiana/Winamac',
        'America/Indianapolis',
        'America/Inuvik',
        'America/Iqaluit',
        'America/Jamaica',
        'America/Jujuy',
        'America/Juneau',
        'America/Kentucky/Louisville',
        'America/Kentucky/Monticello',
        'America/Knox_IN',
        'America/Kralendijk',
        'America/La_Paz',
        'America/Lima',
        'America/Los_Angeles',
        'America/Louisville',
        'America/Lower_Princes',
        'America/Maceio',
        'America/Managua',
        'America/Manaus',
        'America/Marigot',
        'America/Martinique',
        'America/Matamoros',
        'America/Mazatlan',
        'America/Mendoza',
        'America/Menominee',
        'America/Merida',
        'America/Metlakatla',
        'America/Mexico_City',
        'America/Miquelon',
        'America/Moncton',
        'America/Monterrey',
        'America/Montevideo',
        'America/Montreal',
        'America/Montserrat',
        'America/Nassau',
        'America/New_York',
        'America/Nipigon',
        'America/Nome',
        'America/Noronha',
        'America/North_Dakota/Beulah',
        'America/North_Dakota/Center',
        'America/North_Dakota/New_Salem',
        'America/Ojinaga',
        'America/Panama',
        'America/Pangnirtung',
        'America/Paramaribo',
        'America/Phoenix',
        'America/Port-au-Prince',
        'America/Port_of_Spain',
        'America/Porto_Acre',
        'America/Porto_Velho',
        'America/Puerto_Rico',
        'America/Rainy_River',
        'America/Rankin_Inlet',
        'America/Recife',
        'America/Regina',
        'America/Resolute',
        'America/Rio_Branco',
        'America/Rosario',
        'America/Santa_Isabel',
        'America/Santarem',
        'America/Santiago',
        'America/Santo_Domingo',
        'America/Sao_Paulo',
        'America/Scoresbysund',
        'America/Shiprock',
        'America/Sitka',
        'America/St_Barthelemy',
        'America/St_Johns',
        'America/St_Kitts',
        'America/St_Lucia',
        'America/St_Thomas',
        'America/St_Vincent',
        'America/Swift_Current',
        'America/Tegucigalpa',
        'America/Thule',
        'America/Thunder_Bay',
        'America/Tijuana',
        'America/Toronto',
        'America/Tortola',
        'America/Vancouver',
        'America/Virgin',
        'America/Whitehorse',
        'America/Winnipeg',
        'America/Yakutat',
        'America/Yellowknife',
        'Antarctica/Casey',
        'Antarctica/Davis',
        'Antarctica/DumontDUrville',
        'Antarctica/Macquarie',
        'Antarctica/Mawson',
        'Antarctica/McMurdo',
        'Antarctica/Palmer',
        'Antarctica/Rothera',
        'Antarctica/South_Pole',
        'Antarctica/Syowa',
        'Antarctica/Vostok',
        'Arctic/Longyearbyen',
        'Asia/Aden',
        'Asia/Almaty',
        'Asia/Amman',
        'Asia/Anadyr',
        'Asia/Aqtau',
        'Asia/Aqtobe',
        'Asia/Ashgabat',
        'Asia/Ashkhabad',
        'Asia/Baghdad',
        'Asia/Bahrain',
        'Asia/Baku',
        'Asia/Bangkok',
        'Asia/Beirut',
        'Asia/Bishkek',
        'Asia/Brunei',
        'Asia/Calcutta',
        'Asia/Choibalsan',
        'Asia/Chongqing',
        'Asia/Chungking',
        'Asia/Colombo',
        'Asia/Dacca',
        'Asia/Damascus',
        'Asia/Dhaka',
        'Asia/Dili',
        'Asia/Dubai',
        'Asia/Dushanbe',
        'Asia/Gaza',
        'Asia/Harbin',
        'Asia/Hebron',
        'Asia/Ho_Chi_Minh',
        'Asia/Hong_Kong',
        'Asia/Hovd',
        'Asia/Irkutsk',
        'Asia/Istanbul',
        'Asia/Jakarta',
        'Asia/Jayapura',
        'Asia/Jerusalem',
        'Asia/Kabul',
        'Asia/Kamchatka',
        'Asia/Karachi',
        'Asia/Kashgar',
        'Asia/Kathmandu',
        'Asia/Katmandu',
        'Asia/Khandyga',
        'Asia/Kolkata',
        'Asia/Krasnoyarsk',
        'Asia/Kuala_Lumpur',
        'Asia/Kuching',
        'Asia/Kuwait',
        'Asia/Macao',
        'Asia/Macau',
        'Asia/Magadan',
        'Asia/Makassar',
        'Asia/Manila',
        'Asia/Muscat',
        'Asia/Nicosia',
        'Asia/Novokuznetsk',
        'Asia/Novosibirsk',
        'Asia/Omsk',
        'Asia/Oral',
        'Asia/Phnom_Penh',
        'Asia/Pontianak',
        'Asia/Pyongyang',
        'Asia/Qatar',
        'Asia/Qyzylorda',
        'Asia/Rangoon',
        'Asia/Riyadh',
        'Asia/Saigon',
        'Asia/Sakhalin',
        'Asia/Samarkand',
        'Asia/Seoul',
        'Asia/Shanghai',
        'Asia/Singapore',
        'Asia/Taipei',
        'Asia/Tashkent',
        'Asia/Tbilisi',
        'Asia/Tehran',
        'Asia/Tel_Aviv',
        'Asia/Thimbu',
        'Asia/Thimphu',
        'Asia/Tokyo',
        'Asia/Ujung_Pandang',
        'Asia/Ulaanbaatar',
        'Asia/Ulan_Bator',
        'Asia/Urumqi',
        'Asia/Ust-Nera',
        'Asia/Vientiane',
        'Asia/Vladivostok',
        'Asia/Yakutsk',
        'Asia/Yekaterinburg',
        'Asia/Yerevan',
        'Atlantic/Azores',
        'Atlantic/Bermuda',
        'Atlantic/Canary',
        'Atlantic/Cape_Verde',
        'Atlantic/Faeroe',
        'Atlantic/Faroe',
        'Atlantic/Jan_Mayen',
        'Atlantic/Madeira',
        'Atlantic/Reykjavik',
        'Atlantic/South_Georgia',
        'Atlantic/St_Helena',
        'Atlantic/Stanley',
        'Australia/ACT',
        'Australia/Adelaide',
        'Australia/Brisbane',
        'Australia/Broken_Hill',
        'Australia/Canberra',
        'Australia/Currie',
        'Australia/Darwin',
        'Australia/Eucla',
        'Australia/Hobart',
        'Australia/LHI',
        'Australia/Lindeman',
        'Australia/Lord_Howe',
        'Australia/Melbourne',
        'Australia/NSW',
        'Australia/North',
        'Australia/Perth',
        'Australia/Queensland',
        'Australia/South',
        'Australia/Sydney',
        'Australia/Tasmania',
        'Australia/Victoria',
        'Australia/West',
        'Australia/Yancowinna',
        'Brazil/Acre',
        'Brazil/DeNoronha',
        'Brazil/East',
        'Brazil/West',
        'Canada/Atlantic',
        'Canada/Central',
        'Canada/East-Saskatchewan',
        'Canada/Eastern',
        'Canada/Mountain',
        'Canada/Newfoundland',
        'Canada/Pacific',
        'Canada/Saskatchewan',
        'Canada/Yukon',
        'Chile/Continental',
        'Chile/EasterIsland',
        'Europe/Amsterdam',
        'Europe/Andorra',
        'Europe/Athens',
        'Europe/Belfast',
        'Europe/Belgrade',
        'Europe/Berlin',
        'Europe/Bratislava',
        'Europe/Brussels',
        'Europe/Bucharest',
        'Europe/Budapest',
        'Europe/Busingen',
        'Europe/Chisinau',
        'Europe/Copenhagen',
        'Europe/Dublin',
        'Europe/Gibraltar',
        'Europe/Guernsey',
        'Europe/Helsinki',
        'Europe/Isle_of_Man',
        'Europe/Istanbul',
        'Europe/Jersey',
        'Europe/Kaliningrad',
        'Europe/Kiev',
        'Europe/Lisbon',
        'Europe/Ljubljana',
        'Europe/London',
        'Europe/Luxembourg',
        'Europe/Madrid',
        'Europe/Malta',
        'Europe/Mariehamn',
        'Europe/Minsk',
        'Europe/Monaco',
        'Europe/Moscow',
        'Europe/Nicosia',
        'Europe/Oslo',
        'Europe/Paris',
        'Europe/Podgorica',
        'Europe/Prague',
        'Europe/Riga',
        'Europe/Rome',
        'Europe/Samara',
        'Europe/San_Marino',
        'Europe/Sarajevo',
        'Europe/Simferopol',
        'Europe/Skopje',
        'Europe/Sofia',
        'Europe/Stockholm',
        'Europe/Tallinn',
        'Europe/Tirane',
        'Europe/Tiraspol',
        'Europe/Uzhgorod',
        'Europe/Vaduz',
        'Europe/Vatican',
        'Europe/Vienna',
        'Europe/Vilnius',
        'Europe/Volgograd',
        'Europe/Warsaw',
        'Europe/Zagreb',
        'Europe/Zaporozhye',
        'Europe/Zurich',
        'Indian/Antananarivo',
        'Indian/Chagos',
        'Indian/Christmas',
        'Indian/Cocos',
        'Indian/Comoro',
        'Indian/Kerguelen',
        'Indian/Mahe',
        'Indian/Maldives',
        'Indian/Mauritius',
        'Indian/Mayotte',
        'Indian/Reunion',
        'Mexico/BajaNorte',
        'Mexico/BajaSur',
        'Mexico/General',
        'Pacific/Apia',
        'Pacific/Auckland',
        'Pacific/Chatham',
        'Pacific/Chuuk',
        'Pacific/Easter',
        'Pacific/Efate',
        'Pacific/Enderbury',
        'Pacific/Fakaofo',
        'Pacific/Fiji',
        'Pacific/Funafuti',
        'Pacific/Galapagos',
        'Pacific/Gambier',
        'Pacific/Guadalcanal',
        'Pacific/Guam',
        'Pacific/Honolulu',
        'Pacific/Johnston',
        'Pacific/Kiritimati',
        'Pacific/Kosrae',
        'Pacific/Kwajalein',
        'Pacific/Majuro',
        'Pacific/Marquesas',
        'Pacific/Midway',
        'Pacific/Nauru',
        'Pacific/Niue',
        'Pacific/Norfolk',
        'Pacific/Noumea',
        'Pacific/Pago_Pago',
        'Pacific/Palau',
        'Pacific/Pitcairn',
        'Pacific/Pohnpei',
        'Pacific/Ponape',
        'Pacific/Port_Moresby',
        'Pacific/Rarotonga',
        'Pacific/Saipan',
        'Pacific/Samoa',
        'Pacific/Tahiti',
        'Pacific/Tarawa',
        'Pacific/Tongatapu',
        'Pacific/Truk',
        'Pacific/Wake',
        'Pacific/Wallis',
        'Pacific/Yap',
    ],
    AF: ['Asia/Kabul'],
    AX: ['Europe/Mariehamn'],
    AL: ['Europe/Tirane'],
    DZ: ['Africa/Algiers'],
    AS: ['Pacific/Pago_Pago'],
    AD: ['Europe/Andorra'],
    AO: ['Africa/Luanda'],
    AI: ['America/Anguilla'],
    AQ: [
        'Antarctica/McMurdo',
        'Antarctica/South_Pole',
        'Antarctica/Rothera',
        'Antarctica/Palmer',
        'Antarctica/Mawson',
        'Antarctica/Davis',
        'Antarctica/Casey',
        'Antarctica/Vostok',
        'Antarctica/DumontDUrville',
        'Antarctica/Syowa',
    ],
    AG: ['America/Antigua'],
    AR: [
        'America/Argentina/Buenos_Aires',
        'America/Argentina/Cordoba',
        'America/Argentina/Salta',
        'America/Argentina/Jujuy',
        'America/Argentina/Tucuman',
        'America/Argentina/Catamarca',
        'America/Argentina/La_Rioja',
        'America/Argentina/San_Juan',
        'America/Argentina/Mendoza',
        'America/Argentina/San_Luis',
        'America/Argentina/Rio_Gallegos',
        'America/Argentina/Ushuaia',
    ],
    AM: ['Asia/Yerevan'],
    AW: ['America/Aruba'],
    AU: [
        'Australia/Lord_Howe',
        'Antarctica/Macquarie',
        'Australia/Hobart',
        'Australia/Currie',
        'Australia/Melbourne',
        'Australia/Sydney',
        'Australia/Broken_Hill',
        'Australia/Brisbane',
        'Australia/Lindeman',
        'Australia/Adelaide',
        'Australia/Darwin',
        'Australia/Perth',
        'Australia/Eucla',
    ],
    AT: ['Europe/Vienna'],
    AZ: ['Asia/Baku'],
    BS: ['America/Nassau'],
    BH: ['Asia/Bahrain'],
    BD: ['Asia/Dhaka'],
    BB: ['America/Barbados'],
    BY: ['Europe/Minsk'],
    BE: ['Europe/Brussels'],
    BZ: ['America/Belize'],
    BJ: ['Africa/Porto-Novo'],
    BM: ['Atlantic/Bermuda'],
    BT: ['Asia/Thimphu'],
    BO: ['America/La_Paz'],
    BA: ['Europe/Sarajevo'],
    BW: ['Africa/Gaborone'],
    BV: ['None'],
    BR: [
        'America/Noronha',
        'America/Belem',
        'America/Fortaleza',
        'America/Recife',
        'America/Araguaina',
        'America/Maceio',
        'America/Bahia',
        'America/Sao_Paulo',
        'America/Campo_Grande',
        'America/Cuiaba',
        'America/Santarem',
        'America/Porto_Velho',
        'America/Boa_Vista',
        'America/Manaus',
        'America/Eirunepe',
        'America/Rio_Branco',
    ],
    IO: ['Indian/Chagos'],
    BN: ['Asia/Brunei'],
    BG: ['Europe/Sofia'],
    BF: ['Africa/Ouagadougou'],
    BI: ['Africa/Bujumbura'],
    KH: ['Asia/Phnom_Penh'],
    CM: ['Africa/Douala'],
    CA: [
        'America/St_Johns',
        'America/Halifax',
        'America/Glace_Bay',
        'America/Moncton',
        'America/Goose_Bay',
        'America/Blanc-Sablon',
        'America/Montreal',
        'America/Toronto',
        'America/Nipigon',
        'America/Thunder_Bay',
        'America/Iqaluit',
        'America/Pangnirtung',
        'America/Resolute',
        'America/Atikokan',
        'America/Rankin_Inlet',
        'America/Winnipeg',
        'America/Rainy_River',
        'America/Regina',
        'America/Swift_Current',
        'America/Edmonton',
        'America/Cambridge_Bay',
        'America/Yellowknife',
        'America/Inuvik',
        'America/Creston',
        'America/Dawson_Creek',
        'America/Vancouver',
        'America/Whitehorse',
        'America/Dawson',
    ],
    CV: ['Atlantic/Cape_Verde'],
    KY: ['America/Cayman'],
    CF: ['Africa/Bangui'],
    TD: ['Africa/Ndjamena'],
    CL: ['America/Santiago', 'Pacific/Easter'],
    CN: [
        'Asia/Shanghai',
        'Asia/Harbin',
        'Asia/Chongqing',
        'Asia/Urumqi',
        'Asia/Kashgar',
    ],
    CX: ['Indian/Christmas'],
    CC: ['Indian/Cocos'],
    CO: ['America/Bogota'],
    KM: ['Indian/Comoro'],
    CG: ['Africa/Brazzaville'],
    CD: ['Africa/Kinshasa', 'Africa/Lubumbashi'],
    CK: ['Pacific/Rarotonga'],
    CR: ['America/Costa_Rica'],
    CI: ['Africa/Abidjan'],
    HR: ['Europe/Zagreb'],
    CU: ['America/Havana'],
    CY: ['Asia/Nicosia'],
    CZ: ['Europe/Prague'],
    DK: ['Europe/Copenhagen'],
    DJ: ['Africa/Djibouti'],
    DM: ['America/Dominica'],
    DO: ['America/Santo_Domingo'],
    EC: ['America/Guayaquil', 'Pacific/Galapagos'],
    EG: ['Africa/Cairo'],
    SV: ['America/El_Salvador'],
    GQ: ['Africa/Malabo'],
    ER: ['Africa/Asmara'],
    EE: ['Europe/Tallinn'],
    ET: ['Africa/Addis_Ababa'],
    FK: ['Atlantic/Stanley'],
    FO: ['Atlantic/Faroe'],
    FJ: ['Pacific/Fiji'],
    FI: ['Europe/Helsinki'],
    FR: ['Europe/Paris'],
    GF: ['America/Cayenne'],
    PF: ['Pacific/Tahiti', 'Pacific/Marquesas', 'Pacific/Gambier'],
    TF: ['Indian/Kerguelen'],
    GA: ['Africa/Libreville'],
    GM: ['Africa/Banjul'],
    GE: ['Asia/Tbilisi'],
    DE: ['Europe/Berlin', 'Europe/Busingen'],
    GH: ['Africa/Accra'],
    GI: ['Europe/Gibraltar'],
    GR: ['Europe/Athens'],
    GL: [
        'America/Godthab',
        'America/Danmarkshavn',
        'America/Scoresbysund',
        'America/Thule',
    ],
    GD: ['America/Grenada'],
    GP: ['America/Guadeloupe'],
    GU: ['Pacific/Guam'],
    GT: ['America/Guatemala'],
    GG: ['Europe/Guernsey'],
    GN: ['Africa/Conakry'],
    GW: ['Africa/Bissau'],
    GY: ['America/Guyana'],
    HT: ['America/Port-au-Prince'],
    HM: ['None'],
    VA: ['Europe/Vatican'],
    HN: ['America/Tegucigalpa'],
    HK: ['Asia/Hong_Kong'],
    HU: ['Europe/Budapest'],
    IS: ['Atlantic/Reykjavik'],
    IN: ['Asia/Kolkata'],
    ID: ['Asia/Jakarta', 'Asia/Pontianak', 'Asia/Makassar', 'Asia/Jayapura'],
    IR: ['Asia/Tehran'],
    IQ: ['Asia/Baghdad'],
    IE: ['Europe/Dublin'],
    IM: ['Europe/Isle_of_Man'],
    IL: ['Asia/Jerusalem'],
    IT: ['Europe/Rome'],
    JM: ['America/Jamaica'],
    JP: ['Asia/Tokyo'],
    JE: ['Europe/Jersey'],
    JO: ['Asia/Amman'],
    KZ: [
        'Asia/Almaty',
        'Asia/Qyzylorda',
        'Asia/Aqtobe',
        'Asia/Aqtau',
        'Asia/Oral',
    ],
    KE: ['Africa/Nairobi'],
    KI: ['Pacific/Tarawa', 'Pacific/Enderbury', 'Pacific/Kiritimati'],
    KP: ['Asia/Pyongyang'],
    KR: ['Asia/Seoul'],
    KW: ['Asia/Kuwait'],
    KG: ['Asia/Bishkek'],
    LA: ['Asia/Vientiane'],
    LV: ['Europe/Riga'],
    LB: ['Asia/Beirut'],
    LS: ['Africa/Maseru'],
    LR: ['Africa/Monrovia'],
    LY: ['Africa/Tripoli'],
    LI: ['Europe/Vaduz'],
    LT: ['Europe/Vilnius'],
    LU: ['Europe/Luxembourg'],
    MO: ['Asia/Macau'],
    MK: ['Europe/Skopje'],
    MG: ['Indian/Antananarivo'],
    MW: ['Africa/Blantyre'],
    MY: ['Asia/Kuala_Lumpur', 'Asia/Kuching'],
    MV: ['Indian/Maldives'],
    ML: ['Africa/Bamako'],
    MT: ['Europe/Malta'],
    MH: ['Pacific/Majuro', 'Pacific/Kwajalein'],
    MQ: ['America/Martinique'],
    MR: ['Africa/Nouakchott'],
    MU: ['Indian/Mauritius'],
    YT: ['Indian/Mayotte'],
    MX: [
        'America/Mexico_City',
        'America/Cancun',
        'America/Merida',
        'America/Monterrey',
        'America/Matamoros',
        'America/Mazatlan',
        'America/Chihuahua',
        'America/Ojinaga',
        'America/Hermosillo',
        'America/Tijuana',
        'America/Santa_Isabel',
        'America/Bahia_Banderas',
    ],
    FM: ['Pacific/Chuuk', 'Pacific/Pohnpei', 'Pacific/Kosrae'],
    MD: ['Europe/Chisinau'],
    MC: ['Europe/Monaco'],
    MN: ['Asia/Ulaanbaatar', 'Asia/Hovd', 'Asia/Choibalsan'],
    ME: ['Europe/Podgorica'],
    MS: ['America/Montserrat'],
    MA: ['Africa/Casablanca'],
    MZ: ['Africa/Maputo'],
    MM: ['Asia/Rangoon'],
    NA: ['Africa/Windhoek'],
    NR: ['Pacific/Nauru'],
    NP: ['Asia/Kathmandu'],
    NL: ['Europe/Amsterdam'],
    AN: ['None'],
    NC: ['Pacific/Noumea'],
    NZ: ['Pacific/Auckland', 'Pacific/Chatham'],
    NI: ['America/Managua'],
    NE: ['Africa/Niamey'],
    NG: ['Africa/Lagos'],
    NU: ['Pacific/Niue'],
    NF: ['Pacific/Norfolk'],
    MP: ['Pacific/Saipan'],
    NO: ['Europe/Oslo'],
    OM: ['Asia/Muscat'],
    PK: ['Asia/Karachi'],
    PW: ['Pacific/Palau'],
    PS: ['Asia/Gaza', 'Asia/Hebron'],
    PA: ['America/Panama'],
    PG: ['Pacific/Port_Moresby'],
    PY: ['America/Asuncion'],
    PE: ['America/Lima'],
    PH: ['Asia/Manila'],
    PN: ['Pacific/Pitcairn'],
    PL: ['Europe/Warsaw'],
    PT: ['Europe/Lisbon', 'Atlantic/Madeira', 'Atlantic/Azores'],
    PR: ['America/Puerto_Rico'],
    QA: ['Asia/Qatar'],
    RE: ['Indian/Reunion'],
    RO: ['Europe/Bucharest'],
    RU: [
        'Europe/Kaliningrad',
        'Europe/Moscow',
        'Europe/Volgograd',
        'Europe/Samara',
        'Asia/Yekaterinburg',
        'Asia/Omsk',
        'Asia/Novosibirsk',
        'Asia/Novokuznetsk',
        'Asia/Krasnoyarsk',
        'Asia/Irkutsk',
        'Asia/Yakutsk',
        'Asia/Khandyga',
        'Asia/Vladivostok',
        'Asia/Sakhalin',
        'Asia/Ust-Nera',
        'Asia/Magadan',
        'Asia/Kamchatka',
        'Asia/Anadyr',
    ],
    RW: ['Africa/Kigali'],
    BL: ['America/St_Barthelemy'],
    SH: ['Atlantic/St_Helena'],
    KN: ['America/St_Kitts'],
    LC: ['America/St_Lucia'],
    MF: ['America/Marigot'],
    PM: ['America/Miquelon'],
    VC: ['America/St_Vincent'],
    WS: ['Pacific/Apia'],
    SM: ['Europe/San_Marino'],
    ST: ['Africa/Sao_Tome'],
    SA: ['Asia/Riyadh'],
    SN: ['Africa/Dakar'],
    RS: ['Europe/Belgrade'],
    SC: ['Indian/Mahe'],
    SL: ['Africa/Freetown'],
    SG: ['Asia/Singapore'],
    SK: ['Europe/Bratislava'],
    SI: ['Europe/Ljubljana'],
    SB: ['Pacific/Guadalcanal'],
    SO: ['Africa/Mogadishu'],
    ZA: ['Africa/Johannesburg'],
    GS: ['Atlantic/South_Georgia'],
    ES: ['Europe/Madrid', 'Africa/Ceuta', 'Atlantic/Canary'],
    LK: ['Asia/Colombo'],
    SD: ['Africa/Khartoum'],
    SR: ['America/Paramaribo'],
    SJ: ['Arctic/Longyearbyen'],
    SZ: ['Africa/Mbabane'],
    SE: ['Europe/Stockholm'],
    CH: ['Europe/Zurich'],
    SY: ['Asia/Damascus'],
    TW: ['Asia/Taipei'],
    TJ: ['Asia/Dushanbe'],
    TZ: ['Africa/Dar_es_Salaam'],
    TH: ['Asia/Bangkok'],
    TL: ['Asia/Dili'],
    TG: ['Africa/Lome'],
    TK: ['Pacific/Fakaofo'],
    TO: ['Pacific/Tongatapu'],
    TT: ['America/Port_of_Spain'],
    TN: ['Africa/Tunis'],
    TR: ['Europe/Istanbul'],
    TM: ['Asia/Ashgabat'],
    TC: ['America/Grand_Turk'],
    TV: ['Pacific/Funafuti'],
    UG: ['Africa/Kampala'],
    UA: [
        'Europe/Kiev',
        'Europe/Uzhgorod',
        'Europe/Zaporozhye',
        'Europe/Simferopol',
    ],
    AE: ['Asia/Dubai'],
    GB: ['Europe/London'],
    US: [
        'America/New_York',
        'America/Detroit',
        'America/Kentucky/Louisville',
        'America/Kentucky/Monticello',
        'America/Indiana/Indianapolis',
        'America/Indiana/Vincennes',
        'America/Indiana/Winamac',
        'America/Indiana/Marengo',
        'America/Indiana/Petersburg',
        'America/Indiana/Vevay',
        'America/Chicago',
        'America/Indiana/Tell_City',
        'America/Indiana/Knox',
        'America/Menominee',
        'America/North_Dakota/Center',
        'America/North_Dakota/New_Salem',
        'America/North_Dakota/Beulah',
        'America/Denver',
        'America/Boise',
        'America/Shiprock',
        'America/Phoenix',
        'America/Los_Angeles',
        'America/Anchorage',
        'America/Juneau',
        'America/Sitka',
        'America/Yakutat',
        'America/Nome',
        'America/Adak',
        'America/Metlakatla',
        'Pacific/Honolulu',
    ],
    UM: ['Pacific/Johnston', 'Pacific/Midway', 'Pacific/Wake'],
    UY: ['America/Montevideo'],
    UZ: ['Asia/Samarkand', 'Asia/Tashkent'],
    VU: ['Pacific/Efate'],
    VE: ['America/Caracas'],
    VN: ['Asia/Ho_Chi_Minh'],
    VG: ['America/Tortola'],
    VI: ['America/St_Thomas'],
    WF: ['Pacific/Wallis'],
    EH: ['Africa/El_Aaiun'],
    YE: ['Asia/Aden'],
    ZM: ['Africa/Lusaka'],
    ZW: ['Africa/Harare'],
}

export const vesselIconList = [
    { icon: 'sealogs-sl-boat1.svg', title: 'sealogs sl boat1' },
    { icon: 'sealogs-sl-boat2.svg', title: 'sealogs sl boat2' },
    { icon: 'flaticon-boat.svg', title: 'flaticon boat' },
    { icon: 'flaticon-boat-1.svg', title: 'flaticon boat 1' },
    { icon: 'flaticon-boat-2.svg', title: 'flaticon boat 2' },
    { icon: 'flaticon-boat-3.svg', title: 'flaticon boat 3' },
    { icon: 'flaticon-boat-4.svg', title: 'flaticon boat 4' },
    { icon: 'flaticon-boat-5.svg', title: 'flaticon boat 5' },
    { icon: 'flaticon-boat-6.svg', title: 'flaticon boat 6' },
    { icon: 'flaticon-boat-7.svg', title: 'flaticon boat 7' },
    { icon: 'flaticon-boat-8.svg', title: 'flaticon boat 8' },
    { icon: 'flaticon-boat-11.svg', title: 'flaticon boat 11' },
    { icon: 'flaticon-boat-12.svg', title: 'flaticon boat 12' },
    { icon: 'flaticon-boat-13.svg', title: 'flaticon boat 13' },
    { icon: 'flaticon-boat-14.svg', title: 'flaticon boat 14' },
    { icon: 'flaticon-boat-15.svg', title: 'flaticon boat 15' },
    { icon: 'flaticon-boat-16.svg', title: 'flaticon boat 16' },
    { icon: 'flaticon-boat-17.svg', title: 'flaticon boat 17' },
    { icon: 'flaticon-boat-18.svg', title: 'flaticon boat 18' },
    { icon: 'flaticon-boat-19.svg', title: 'flaticon boat 19' },
    { icon: 'flaticon-boat-20.svg', title: 'flaticon boat 20' },
    { icon: 'flaticon-boat-21.svg', title: 'flaticon boat 21' },
    { icon: 'flaticon-boat-22.svg', title: 'flaticon boat 22' },
    { icon: 'flaticon-boat-23.svg', title: 'flaticon boat 23' },
    { icon: 'flaticon-boat-24.svg', title: 'flaticon boat 24' },
]
