export const LogBookFields = [
    {
        label: 'Crew Members',
        items: [
            { value: 'CrewMemberID', label: 'Crew member', active: true },
            { value: 'DutyPerformedID', label: 'Position', active: true },
            { value: 'PunchIn', label: 'Sign In', active: true },
            { value: 'PunchOut', label: 'Sign Out', active: true },
            { value: 'DutyHours', label: 'Helm Time', active: true },
            { value: 'WorkDetails', label: 'Details', active: true },
        ],
    },
    {
        label: 'Crew Training',
        items: [
            { value: 'TrainerID', label: 'Trainer', active: true },
            {
                value: 'TrainingTypes',
                label: 'Nature of Training',
                active: true,
            },
            {
                value: 'TrainingLocation',
                label: 'Training Location',
                active: true,
            },
            {
                value: 'TrainingSummary',
                label: 'Training Summary',
                active: true,
            },
            {
                value: 'CrewMemberSignatures',
                label: 'Crew Members',
                active: true,
            },
        ],
    },
    {
        label: 'Engine Log',
        items: [
            { value: 'HoursStart', label: 'Hours Start', active: true },
            { value: 'HoursEnd', label: 'Hours End', active: true },
            { value: 'HoursRun', label: 'Hours Run', active: true },
            { value: 'TotalHours', label: 'Total Hours', active: true },
            {
                value: 'FuelTankStartStops',
                label: 'Fuel Records',
                active: true,
            },
            { value: 'NauticalMiles', label: 'Nautical Miles', active: true },
            { value: 'FuelStart', label: 'Fuel Start', active: true },
            { value: 'FuelEnd', label: 'Fuel End', active: true },
            { value: 'FuelAdded', label: 'Fuel Added', active: true },
            { value: 'FuelUsed', label: 'Fuel Used', active: true },
            { value: 'FuelTemp', label: 'Fuel Temp', active: true },
            { value: 'FuelPressure', label: 'Fuel Pressure', active: true },
            {
                value: 'FuelDiffPressure',
                label: 'Fuel Diff Pressure',
                active: true,
            },
            { value: 'FuelRate', label: 'Fuel Rate', active: true },
            {
                value: 'FuelDayTankLevel',
                label: 'Fuel Day Tank Level',
                active: true,
            },
            {
                value: 'HeaderTankLevel',
                label: 'Header Tank Level',
                active: true,
            },
            {
                value: 'EngineFluidRecords',
                label: 'Engine Fluid Records',
                active: true,
            },
            {
                value: 'SewageDisposalRecords',
                label: 'Sewage Disposal Records',
            },
            { value: 'RPM', label: 'RPM', active: true },
            { value: 'Boost', label: 'Boost', active: true },
            { value: 'ManifoldTemp', label: 'Manifold Temp', active: true },
            { value: 'GenSetTemp', label: 'Generator Temp', active: true },
            { value: 'CoolantTemp', label: 'Coolant Temp', active: true },
            {
                value: 'CoolantLevelOK',
                label: 'Coolant Level Ok',
                active: true,
            },
            {
                value: 'ThrustBearingTemp',
                label: 'Thrust Bearing Temp',
                active: true,
            },
            {
                value: 'ShaftBearingTemp',
                label: 'Shaft Bearing Temp',
                active: true,
            },
            { value: 'OilLevelOK', label: 'Oil Level Ok', active: true },
            { value: 'OilPressure', label: 'Oil Pressure', active: true },
            {
                value: 'LubeOilLevelOK',
                label: 'Lube Oil Level Ok',
                active: true,
            },
            { value: 'LubeOilTemp', label: 'Lube Oil Temp', active: true },
            {
                value: 'LubeOilPressure',
                label: 'Lube Oil Pressure',
                active: true,
            },
            {
                value: 'LubeFilterPressure',
                label: 'Lube Filter Pressure',
                active: true,
            },
            { value: 'Volts', label: 'Volts', active: true },
            { value: 'KWLoad', label: 'Kilo Watt Load', active: true },
            {
                value: 'OverboardPressure',
                label: 'Overboard Pressure',
                active: true,
            },
            {
                value: 'OverboardDischarge',
                label: 'Overboard Discharge',
                active: true,
            },
            { value: 'Comments', label: 'Comments', active: true },
            { value: 'Signature', label: 'Signature', active: true },
        ],
    },
    {
        label: 'Engineering Details',
        items: [
            { value: 'Date', label: 'Date', active: true },
            { value: 'EngineerComments', label: 'Comments', active: true },
            { value: 'EngineerWorkOrders', label: 'Work Orders', active: true },
            {
                value: 'VehicleDutySessions',
                label: 'Vessel Duty Session',
                active: true,
            },
            {
                value: 'EngineRunningChecks',
                label: 'Engine Running Checks',
                active: true,
            },
            { value: 'SMURecords', label: 'SMU Meter Readings', active: true },
            { value: 'ManifoldTemp', label: 'Manifold Temp', active: true },
            { value: 'GenSetTemp', label: 'Generator Temp', active: true },
            { value: 'CoolantTemp', label: 'Coolant Temp', active: true },
            { value: 'FuelTemp', label: 'Fuel Temp', active: true },
            {
                value: 'ThrustBearingTemp',
                label: 'Thrust Bearing Temp',
                active: true,
            },
            {
                value: 'ShaftBearingTemp',
                label: 'Shaft Bearing Temp',
                active: true,
            },
            { value: 'OilPressure', label: 'Oil Pressure', active: true },
            { value: 'FuelPressure', label: 'Fuel Pressure', active: true },
            { value: 'FuelRate', label: 'Fuel Rate', active: true },
            { value: 'Volts', label: 'Volts', active: true },
            { value: 'KWLoad', label: 'Kilo Watt Load', active: true },
            {
                value: 'OverboardPressure',
                label: 'Overboard Pressure',
                active: true,
            },
            {
                value: 'OverboardDischarge',
                label: 'Overboard Discharge',
                active: true,
            },
            { value: 'Pyros', label: 'Pyros', active: true },
            { value: 'Boost', label: 'Boost', active: true },
            { value: 'WaterTemp', label: 'Water Temp', active: true },
            { value: 'AirTemp', label: 'Air Temp', active: true },
            { value: 'RPM', label: 'RPM', active: true },
            { value: 'Rack', label: 'Rack', active: true },
            { value: 'GenSetOP', label: 'Genset O/P', active: true },
            { value: 'GenSetWT', label: 'Genset W/T', active: true },
            { value: 'GearboxOP', label: 'Gearbox O/P', active: true },
            { value: 'GearboxCLOP', label: 'Gearbox C/L/O', active: true },
            { value: 'GearboxOT', label: 'Gearbox O/T', active: true },
            { value: 'HRPOP', label: 'HRP O/P', active: true },
            { value: 'SeaLogsMemberID', label: 'Engineer', active: true },
        ],
    },
    {
        label: 'Fuel',
        items: [
            {
                value: 'HazardousSubstanceRecords',
                label: 'Hazardous Substances',
            },
            {
                value: 'FuelTankStartStops',
                label: 'Fuel Records',
                active: true,
            },
            {
                value: 'EngineFluidRecords',
                label: 'Engine Fluid Records',
                active: true,
            },
            {
                value: 'SewageDisposalRecords',
                label: 'Sewage Disposal Records',
            },
            { value: 'FuelTankID', label: 'Fuel Tank', active: true },
            { value: 'Start', label: 'Start Level', active: true },
            { value: 'End', label: 'End Level', active: true },
            { value: 'Added', label: 'Fuel Added', active: true },
        ],
    },
    {
        label: "Shipping Log's",
        items: [
            { value: 'Title', label: 'Let Go - Tie Up', active: true },
            { value: 'StartTitle', label: 'Let Go', active: true },
            { value: 'StopTitle', label: 'Tie Up', active: true },
            { value: 'DurationTitle', label: 'Duration', active: true },
            {
                value: 'ChecksCompleted',
                label: 'Checks completed in accordance to Vessel',
            },
            { value: 'Tides', label: 'Tides', active: true },
            { value: 'PilotTransfers', label: 'Pilot Transfers', active: true },
            { value: 'ShipTugs', label: 'Tug Logs', active: true },
            { value: 'OtherActivities', label: 'Other Activity', active: true },
            { value: 'PPBTransfers', label: 'PPB Transfers', active: true },
            { value: 'MasterID', label: 'Master', active: true },
            { value: 'TripCrewList', label: 'Crew List', active: true },
            { value: 'SafetyKayakers', label: 'Engineers', active: true },
            { value: 'FuelUsed', label: 'Fuel Used', active: true },
            { value: 'Supernumerary', label: 'Supernumerary', active: true },
            { value: 'Comments', label: 'Comments', active: true },
            { value: 'Signature', label: 'Signature Initial', active: true },
        ],
    },
    {
        label: 'Supernumerary',
        items: [
            { value: 'FirstName', label: 'First Name', active: true },
            { value: 'Surname', label: 'Surname', active: true },
            { value: 'Signature', label: 'Signature', active: true },
        ],
    },
    {
        label: 'Trip Log',
        items: [
            { value: 'DepartFrom', label: 'Depart From', active: true },
            { value: 'DepartTime', label: 'Depart Time', active: true },
            { value: 'Depart', label: 'Depart', active: true },
            { value: 'Title', label: 'Depart Location', active: true },
            { value: 'From', label: 'From', active: true },
            {
                value: 'FromCreatesNewGeoLocation',
                label: 'Save This Location for Future Use',
            },
            {
                value: 'ExpectedNextContact',
                label: 'Next Expected Contact Time',
            },
            { value: 'LetGoTieUp', label: 'Depart - Arrive', active: true },
            { value: 'PositionLogs', label: 'Position Logs', active: true },
            { value: 'DangerousGoods', label: 'Dangerous Goods', active: true },
            {
                value: 'DailyChecksCompleted',
                label: 'Checks completed in accordance to Vessel',
            },
            { value: 'PaxJoinedBreakDown', label: 'Pax Joined', active: true },
            { value: 'PaxJoinedAdult', label: 'Adult', active: true },
            { value: 'PaxJoinedChild', label: 'Child', active: true },
            { value: 'PaxJoinedYouth', label: 'Youth', active: true },
            { value: 'PaxJoinedVoucher', label: 'Voucher', active: true },
            { value: 'PaxJoinedFOC', label: 'F.O.C.', active: true },
            { value: 'PaxJoinedStaff', label: 'Staff', active: true },
            { value: 'PaxJoinedPrePaid', label: 'Prepaid', active: true },
            { value: 'PaxDeparted', label: 'Pax Departed', active: true },
            { value: 'NumberPax', label: 'Total Pax Carried', active: true },
            { value: 'VoucherNumber', label: 'Voucher Number', active: true },
            { value: 'SafetyBriefing', label: 'Safety Briefing', active: true },
            {
                value: 'SpeedExemption',
                label: 'Speed Exemption Used?',
                active: true,
            },
            {
                value: 'SpeedExemptionCorridorID',
                label: 'Corridor',
                active: true,
            },
            { value: 'SpeedExemptionReasonID', label: 'Reason', active: true },
            { value: 'VehiclesJoined', label: 'Vehicles Joined', active: true },
            {
                value: 'VehiclesDeparted',
                label: 'Vehicles Departed',
                active: true,
            },
            {
                value: 'TotalVehiclesCarried',
                label: 'Total Vehicles Carried',
                active: true,
            },
            { value: 'VOB', label: 'Vehicles Onboard', active: true },
            { value: 'TripReport_Stops', label: 'Trip Stops', active: true },
            { value: 'VehicleDrivers', label: 'Vehicle Drivers', active: true },
            { value: 'TripEvents', label: 'Trip Events', active: true },
            {
                value: 'IncidentReports',
                label: 'Incident Report',
                active: true,
            },
            { value: 'HazardReports', label: 'Hazard Report', active: true },
            { value: 'MasterID', label: 'Master', active: true },
            { value: 'LeadGuideID', label: 'Lead Guide', active: true },
            { value: 'TripCrewList', label: 'Crew List', active: true },
            { value: 'SafetyKayakers', label: 'Safety Kayakers', active: true },
            { value: 'ArriveTime', label: 'Arrival Time', active: true },
            { value: 'Arrive', label: 'Arrive', active: true },
            {
                value: 'SAVELOCATIONFORFUTURE',
                label: 'Save This Location for Future Use',
            },
            { value: 'To', label: 'Destination', active: true },
            { value: 'ArriveTo', label: 'Arrived To', active: true },
            { value: 'ToLat', label: 'Latitude', active: true },
            { value: 'ToLong', label: 'Longitude', active: true },
            { value: 'Comments', label: 'Comments', active: true },
            { value: 'Signature', label: 'Signature Initial', active: true },
            { value: 'RIVERFLOW', label: 'River Flow', active: true },
            { value: 'POB', label: 'Passengers Onboard', active: true },
        ],
    },
    {
        label: 'Daily Checks',
        items: [
            { value: 'CheckTime', label: 'Check Time', active: true },
            { value: 'BilgeLevels', label: 'Bilge Levels', active: true },
            { value: 'BilgePumps', label: 'Bilge Pumps', active: true },
            { value: 'Hull', label: 'Hull and Superstructure', active: true },
            {
                value: 'NavEquipment',
                label: 'Navigation Equipment',
                active: true,
            },
            {
                value: 'OilAndWater',
                label: 'Machinery Oil and Water',
                active: true,
            },
            {
                value: 'EngineRoomChecks',
                label: 'Engine Room Checks',
                active: true,
            },
            {
                value: 'SafetyEquipment',
                label: 'Safety Equipment',
                active: true,
            },
            {
                value: 'DriveShafts',
                label: 'Drive shafts, gearbox, propeller, skeg',
                active: true,
            },
            { value: 'Wiring', label: 'Wiring', active: true },
            { value: 'Batteries', label: 'Batteries', active: true },
            {
                value: 'ChecksWithManual',
                label: 'Checks in Accordance With',
                active: true,
            },
            {
                value: 'BeltsHosesClamps',
                label: 'Belts, Hoses, Clamps and Fittings',
            },
            { value: 'Cabin', label: 'Cabin', active: true },
            { value: 'Floor', label: 'Floor', active: true },
            { value: 'EngineMounts', label: 'Engine Mounts', active: true },
            { value: 'EngineOil', label: 'Engine Oil', active: true },
            {
                value: 'EngineTellTale',
                label: 'Engine Tell Tale Signs',
                active: true,
            },
            {
                value: 'EngineIsFit',
                label: 'Engine Controls Tested',
                active: true,
            },
            { value: 'SteeringFluid', label: 'Steering Fluid', active: true },
            { value: 'SteeringRams', label: 'Steering Rams', active: true },
            { value: 'SteeringIsFit', label: 'Steering Checked', active: true },
            { value: 'EPIRB', label: 'EPIRB', active: true },
            { value: 'LifeJackets', label: 'Life Jackets', active: true },
            {
                value: 'FireExtinguisher',
                label: 'Fire Essentials',
                active: true,
            },
            {
                value: 'ForwardAndReverseBelts',
                label: 'Forward & Reverse',
                active: true,
            },
            { value: 'SteeringTiller', label: 'Steering, Tiller, Arm Bolts' },
            {
                value: 'CablesFRPullies',
                label: 'Cables & Pullies',
                active: true,
            },
            {
                value: 'ThrottleAndCable',
                label: 'Throttle and cable checks, sand traps',
                active: true,
            },
            { value: 'SandTraps', label: 'Sand Traps', active: true },
            {
                value: 'UnitTransomBolts',
                label: 'Unit-Transom Bolts',
                active: true,
            },
            { value: 'CotterPins', label: 'Cotter Pins', active: true },
            {
                value: 'ReverseBucketAndRam',
                label: 'Reverse Bucket & Rams',
                active: true,
            },
            {
                value: 'NozzleAndBearings',
                label: 'Nozzle & Bearings',
                active: true,
            },
            {
                value: 'TailHousing',
                label: 'Tail Housing & Bolts',
                active: true,
            },
            { value: 'WeatherSummary', label: 'Weather Forecast Summary' },
            { value: 'WindDirection', label: 'Wind Direction', active: true },
            { value: 'WindStrength', label: 'Wind Strength', active: true },
            { value: 'Swell', label: 'Sea Swell', active: true },
            { value: 'TimeHighTide', label: 'High Tide Time', active: true },
            { value: 'LevelHighTide', label: 'High Tide Level', active: true },
            { value: 'TimeLowTide', label: 'Low Tide Time', active: true },
            { value: 'LevelLowTide', label: 'Low Tide Level', active: true },
            { value: 'Tides', label: 'Tide Predictions', active: true },
            { value: 'MasterID', label: 'Crew Member', active: true },
            {
                value: 'Comments',
                label: 'Maintenance / Corrective Actions',
            },
            { value: 'Signature', label: 'Signature', active: true },
        ],
    },
    {
        label: 'Voyage Summary',
        items: [
            {
                value: 'Activities',
                label: 'Activities Undertaken',
                active: true,
            },
            { value: 'CourseSteered', label: 'Course Steered', active: true },
            {
                value: 'CourseOverGround',
                label: 'Course Over Ground',
                active: true,
            },
            {
                value: 'ChangesToPlan',
                label: 'Changes To Voyage',
                active: true,
            },
            {
                value: 'SpeedOverGround',
                label: 'Speed Over Ground',
                active: true,
            },
            { value: 'VesselRPM', label: 'Vessel RPM', active: true },
            {
                value: 'TypeOfSteering',
                label: 'Type Of Steering',
                active: true,
            },
            { value: 'VoyageDistance', label: 'Voyage Distance', active: true },
            { value: 'Comments', label: 'Unusual Occurrences', active: true },
            { value: 'Oktas', label: 'Cloud Cover', active: true },
            {
                value: 'WindStrength',
                label: 'Wind Strength (Kts)',
                active: true,
            },
            { value: 'WindDirection', label: 'Wind Direction', active: true },
            { value: 'Precipitation', label: 'Precipitation', active: true },
            { value: 'Pressure', label: 'Barometeric Pressure', active: true },
            { value: 'Visibility', label: 'Visibility', active: true },
            { value: 'Swell', label: 'Swell', active: true },
            { value: 'SeaState', label: 'Sea State', active: true },
            {
                value: 'WeatherComments',
                label: 'Comments on Conditions',
                active: true,
            },
            {
                value: 'ForecastComment',
                label: 'Forecast comments',
                active: true,
            },
            { value: 'WeatherReports', label: 'Weather Reports', active: true },
            { value: 'Tides', label: 'Tide Predictions', active: true },
        ],
    },
]
